### ISSUE TITLE
Runtime Exception when Screen sleeps

### ISSUE THREAD

**Issue by ad3bay0** [doo/Scanbot-SDK-Examples#28]
I get the following runtime exception when the screen sleeps:

**E/CameraView: Could not work with camera parameters?
              java.lang.RuntimeException: Method called after release()
                  at android.hardware.Camera.native_getParameters(Native Method)
                  at android.hardware.Camera.getParameters(Camera.java:1759)
                  at com.commonsware.cwac.camera.CameraView.getCameraParameters(CameraView.java:109)
                  at com.commonsware.cwac.camera.CameraView.onMeasure(CameraView.java:245)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                  at net.doo.snap.camera.ScanbotCameraView.onMeasure(SourceFile:89)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                  at android.view.View.measure(View.java:17478)
                  at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                  at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
                  at android.view.View.measure(View.java:17478)
                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2259)
                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1388)
                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1587)
                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6567)
                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
                  at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                  at android.view.Choreographer.doFrame(Choreographer.java:573)
                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
                  at android.os.Handler.handleCallback(Handler.java:733)
                  at android.os.Handler.dispatchMessage(Handler.java:95)
                  at android.os.Looper.loop(Looper.java:136)
                  at android.app.ActivityThread.main(ActivityThread.java:5476)
                  at java.lang.reflect.Method.invokeNative(Native Method)
                  at java.lang.reflect.Method.invoke(Method.java:515)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                  at dalvik.system.NativeStart.main(Native Method)**

**Comment by eddyfrank** [comment]
Hi @ad3bay0 ,

this exception is known to us. We catch and log it inside our SDK. But we do not rethrow it, since it is not real issue. So you can just ignore it for now. There must be another cause for your crash.
