### ISSUE TITLE
Changing Activity from PictureCallback.onPictureTaken

### ISSUE THREAD

**Issue by rschweda** [doo/Scanbot-SDK-Examples#31]
Hi there,
a customer asked us to replace his existing document scanning solution with Scanbot. After taking a picture we would like to change to another activity. We run into the following exception:

```takePicture
05-20 12:08:23.122 7607-7692/com.myapp.com I/A: getPictureSize
05-20 12:08:23.183 7607-7833/com.myapp.com I/AUTO_SNAPPING_CONTROLLER$B: handleResult
05-20 12:08:23.185 7607-7833/com.myapp.com I/CAMERA_VIEW$A$3: run
05-20 12:08:23.898 7607-8006/com.myapp.com I/A: saveImage
05-20 12:08:23.908 7607-7607/com.myapp.com I/SCANBOT_CAMERA_VIEW: stopPreview
05-20 12:08:23.933 7607-7607/com.myapp.com I/CAMERA_VIEW: stopPreview
05-20 12:08:24.074 7607-7607/com.myapp.com I/SCANBOT_CAMERA_VIEW: onPause
05-20 12:08:24.077 7607-7607/com.myapp.com I/CAMERA_VIEW: onPause
05-20 12:08:24.081 7607-7607/com.myapp.com I/SensorManager: unregisterListenerImpl++: listener = android.view.OrientationEventListener$SensorEventListenerImpl@6b94eea
05-20 12:08:24.130 7607-7693/com.myapp.com W/OpenGLRenderer: Fail to change FontRenderer cache size, it already initialized
05-20 12:08:24.162 7607-7759/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.162 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.162 7607-7619/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.164 7607-7759/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.164 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.164 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.164 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.165 7607-7619/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.165 7607-7759/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.166 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.166 7607-7619/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] cancelBuffer: BufferQueue has been abandoned
05-20 12:08:24.190 7607-7619/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.191 7607-7759/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.191 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.191 7607-7619/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.192 7607-7759/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.192 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.199 7607-7619/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.199 7607-7618/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.219 7607-7759/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.233 7607-7619/com.myapp.com E/BufferQueueProducer: [SurfaceTexture-0-7607-0] query: BufferQueue has been abandoned
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err: java.lang.RuntimeException: setParameters failed
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err:     at android.hardware.Camera.native_setParameters(Native Method)
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err:     at android.hardware.Camera.setParameters(Camera.java:2604)
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err:     at com.commonsware.cwac.camera.CameraView.setCameraParametersSync(CameraView.java:135)
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err:     at com.commonsware.cwac.camera.CameraView$1.run(CameraView.java:122)
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-20 12:08:24.237 7607-7692/com.myapp.com W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-20 12:08:24.359 7607-8029/com.myapp.com I/VTE: Start thread to notify VTE
05-20 12:08:24.359 7607-8029/com.myapp.com I/Camera: hasFeature com.htc.vtetrue
```
   
Here our code:
   
```@Override
    public void onPictureTaken(byte[] bytes, int rotation) {
       
        final Bitmap bitmap = BitmapFactory.decodeByteArray(bytes, 0, bytes.length, null);
        EditFrameActivity.originalBitmap = bitmap;

        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                final Intent intent = new Intent(ScanActivity.this, EditFrameActivity.class);
                startActivityForResult(intent, 1999);
            }
        });
```

The app does crash sporadically. It seems there is some work going on in the background when we start moving to the new Activity. Any ideas how to solve that? Are there any callbacks for that case?

**Comment by eddyfrank** [comment]
Hi @rschweda ,

please make sure to delegate `onResume` and `onPause` methods of your `Activity` to `ScanbotCameraView` as described here: https://github.com/doo/Scanbot-SDK-Examples/wiki/Using-ScanbotCameraView :
```
@Override
    public void onResume() {
        super.onResume();
        scanbotCameraView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        scanbotCameraView.onPause();
    }
```

The error logs of RuntimeExceptions with messages `setParameters failed` and `Could not work with camera parameters / Camera is being used after Camera.release() was called` are known to us. We catch and log them inside our SDK. But we do not rethrow them, since they are not real issues. So I think there must be another cause for your crash.

(By the way: It is not recommended to handle such big Bitmaps as static variables)
