### ISSUE TITLE
Error inflating class net.doo.snap.camera.ScanbotCameraView

### ISSUE THREAD

**Issue by shanmu9898** [doo/Scanbot-SDK-Examples#34]
I am getting this error  everytime 

FATAL EXCEPTION: main
                                                                                  Process: com.mukesh.android.scanbot_test4, PID: 24813
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mukesh.android.scanbot_test4/com.mukesh.android.scanbot_test4.MainActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class net.doo.snap.camera.ScanbotCameraView
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
                                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                                   Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class net.doo.snap.camera.ScanbotCameraView
                                                                                   Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class net.doo.snap.camera.ScanbotCameraView
                                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                      at com.mukesh.android.scanbot_test4.MainActivity.onCreate(MainActivity.java:28)
                                                                                      at android.app.Activity.performCreate(Activity.java:6684)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
                                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void net.doo.snap.util.log.Logger.logMethod()' on a null object reference
                                                                                      at net.doo.snap.camera.CameraView.a(SourceFile:150)
                                                                                      at net.doo.snap.camera.ScanbotCameraView.initView(SourceFile:72)
                                                                                      at net.doo.snap.camera.ScanbotCameraView.<init>(SourceFile:63)
                                                                                      at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                      at com.mukesh.android.scanbot_test4.MainActivity.onCreate(MainActivity.java:28) 
                                                                                      at android.app.Activity.performCreate(Activity.java:6684) 
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751) 
                                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by eddyfrank** [comment]
Hi @shanmu9898,

looks like the Scanbot SDK was not initialized by your app.
Please make sure to initialize the Scanbot SDK in your `Application` class before you call/use any functions/components of the SDK:

```
public class ExampleApplication extends Application {
    @Override
    public void onCreate() {
        new ScanbotSDKInitializer().initialize(this);
        super.onCreate();
    }
}
```

See our docs: https://github.com/doo/Scanbot-SDK-Examples/wiki/Getting-started#initialize-sdk

For further questions and details about the Scanbot SDK please contact us via sdk@scanbot.io.

Thanks.

Regards,
Eddy

**Comment by eddyfrank** [comment]
The latest Scanbot SDK version (1.26.+) provides better error messages regarding the license check.
